services:
  - type: web
    name: tts-proxy-concat
    env: node
    buildCommand: apt-get update && apt-get install -y ffmpeg && npm install
    startCommand: npm start
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
